package org.trainings.charan.springjdbch2.constants;

public interface EmployeeConstants {
	String GET_ALL_EMPLOYEES = "SELECT * FROM EMPLOYEES";
	String GET_EMPLOYEE_BY_ID = "SELECT * FROM EMPLOYEES WHERE ID=?";
	String INSERT_EMPLOYEE = "INSERT INTO EMPLOYEES(NAME,DOB,EMAIL) VALUES(?,?,?)";
	String UPDATE_EMPLOYEE = "UPDATE EMPLOYEES SET NAME=?,DOB=?,EMAIL=? WHERE ID=?";
	String DELETE_EMPLOYEE = "DELETE FROM EMPLOYEES WHERE ID=?";
	String GET_EMPLOYEE_BY_NAME_AND_EMAIL = "SELECT * FROM EMPLOYEES WHERE NAME = :NAME AND EMAIL=:EMAIL";
	String INSERT_ADDRESS = "INSERT INTO ADDRESS (EMPLOYEE_ID,STREET,CITY,STATE,PINCODE) VALUES(?,?,?,?,?)";
	String QGET_EMPLOYEE_BY_NAME_AND_EMAIL = "SELECT * FROM EMPLOYEES WHERE NAME = ? AND EMAIL=?" ;
}
